packages:
  - "contracts"
  - "apps/dev-console"
  - "apps/api-server"
  - "apps/web-ui"
  - "apps/indexer/event"
  - "apps/indexer/tasks"
  - "packages/db"
  - "packages/chain"
  - "packages/shared/*"
  - "tools/dev-bootstrap"
