export const contestAbi = [
  {
    type: "function",
    name: "config",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { internalType: "address", name: "entryAsset", type: "address" },
      { internalType: "uint256", name: "entryAmount", type: "uint256" },
      { internalType: "address", name: "priceSource", type: "address" },
      { internalType: "address", name: "swapPool", type: "address" },
      { internalType: "uint16", name: "priceToleranceBps", type: "uint16" },
      { internalType: "uint32", name: "settlementWindow", type: "uint32" },
      { internalType: "uint16", name: "maxParticipants", type: "uint16" },
      { internalType: "uint16", name: "topK", type: "uint16" },
    ],
  },
  {
    type: "function",
    name: "participantCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "participantVaults",
    stateMutability: "view",
    inputs: [{ internalType: "address", name: "", type: "address" }],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "vaultAddresses",
    stateMutability: "view",
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    outputs: [{ internalType: "address", name: "", type: "address" }],
  },
  {
    type: "function",
    name: "getVaultContext",
    stateMutability: "view",
    inputs: [{ internalType: "address", name: "vault", type: "address" }],
    outputs: [
      { internalType: "bytes32", name: "vaultId", type: "bytes32" },
      { internalType: "address", name: "owner", type: "address" },
    ],
  },
  {
    type: "function",
    name: "vaultNavs",
    stateMutability: "view",
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "vaultRoiBps",
    stateMutability: "view",
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    outputs: [{ internalType: "int32", name: "", type: "int32" }],
  },
  {
    type: "function",
    name: "vaultFactory",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "address", name: "", type: "address" }],
  },
  {
    type: "function",
    name: "state",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "timeline",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        components: [
          { internalType: "uint64", name: "registeringEnds", type: "uint64" },
          { internalType: "uint64", name: "liveEnds", type: "uint64" },
          { internalType: "uint64", name: "claimEnds", type: "uint64" },
        ],
        internalType: "struct Contest.ContestTimeline",
        name: "",
        type: "tuple",
      },
    ],
  },
  {
    type: "function",
    name: "register",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "freeze",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "settle",
    stateMutability: "nonpayable",
    inputs: [{ internalType: "address", name: "participant", type: "address" }],
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "int32", name: "", type: "int32" },
    ],
  },
  {
    type: "function",
    name: "updateLeaders",
    stateMutability: "nonpayable",
    inputs: [
      {
        components: [
          { internalType: "bytes32", name: "vaultId", type: "bytes32" },
          { internalType: "uint256", name: "nav", type: "uint256" },
          { internalType: "int32", name: "roiBps", type: "int32" },
        ],
        internalType: "struct Contest.LeaderboardUpdate[]",
        name: "updates",
        type: "tuple[]",
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getLeaders",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        components: [
          { internalType: "bytes32", name: "vaultId", type: "bytes32" },
          { internalType: "uint256", name: "nav", type: "uint256" },
          { internalType: "int32", name: "roiBps", type: "int32" },
          { internalType: "uint16", name: "rank", type: "uint16" },
        ],
        internalType: "struct Contest.LeaderboardEntry[]",
        name: "",
        type: "tuple[]",
      },
    ],
  },
  {
    type: "function",
    name: "seal",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "claimFor",
    stateMutability: "nonpayable",
    inputs: [{ internalType: "address", name: "participant", type: "address" }],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "exit",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "prizePool",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalPrizePool",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "leaderboardVersion",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
  },
  {
    type: "event",
    name: "ContestRegistered",
    inputs: [
      { indexed: true, internalType: "bytes32", name: "contestId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "participant", type: "address" },
      { indexed: false, internalType: "address", name: "vault", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ContestFrozen",
    inputs: [
      { indexed: true, internalType: "bytes32", name: "contestId", type: "bytes32" },
      { indexed: false, internalType: "uint64", name: "frozenAt", type: "uint64" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VaultSettled",
    inputs: [
      { indexed: true, internalType: "bytes32", name: "vaultId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "nav", type: "uint256" },
      { indexed: false, internalType: "int32", name: "roiBps", type: "int32" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LeadersUpdated",
    inputs: [
      { indexed: true, internalType: "bytes32", name: "contestId", type: "bytes32" },
      { indexed: false, internalType: "bytes32[]", name: "vaultIds", type: "bytes32[]" },
      { indexed: false, internalType: "uint32", name: "heapVersion", type: "uint32" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ContestSealed",
    inputs: [
      { indexed: true, internalType: "bytes32", name: "contestId", type: "bytes32" },
      { indexed: false, internalType: "uint64", name: "sealedAt", type: "uint64" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RewardClaimed",
    inputs: [
      { indexed: true, internalType: "bytes32", name: "contestId", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "vaultId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VaultExited",
    inputs: [
      { indexed: true, internalType: "bytes32", name: "contestId", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "vaultId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "baseReturned", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "quoteReturned", type: "uint256" },
    ],
    anonymous: false,
  },
] as const;
