export const vaultAbi = [
  {
    type: "function",
    name: "baseAsset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "address", name: "", type: "address" }],
  },
  {
    type: "function",
    name: "quoteAsset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "address", name: "", type: "address" }],
  },
  {
    type: "function",
    name: "baseBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "quoteBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "address", name: "", type: "address" }],
  },
  {
    type: "function",
    name: "contest",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "address", name: "", type: "address" }],
  },
  {
    type: "function",
    name: "swapExact",
    stateMutability: "nonpayable",
    inputs: [
      { internalType: "uint256", name: "amountIn", type: "uint256" },
      { internalType: "uint256", name: "minAmountOut", type: "uint256" },
      { internalType: "bool", name: "swapBaseForQuote", type: "bool" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    outputs: [
      { internalType: "uint256", name: "amountOut", type: "uint256" },
      { internalType: "int32", name: "priceImpactBps", type: "int32" },
    ],
  },
  {
    type: "event",
    name: "VaultSwapped",
    inputs: [
      { indexed: true, internalType: "address", name: "contest", type: "address" },
      { indexed: true, internalType: "address", name: "participant", type: "address" },
      { indexed: true, internalType: "address", name: "pool", type: "address" },
      { indexed: false, internalType: "address", name: "tokenIn", type: "address" },
      { indexed: false, internalType: "address", name: "tokenOut", type: "address" },
      { indexed: false, internalType: "uint256", name: "amountIn", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amountOut", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "twap", type: "uint256" },
      { indexed: false, internalType: "int32", name: "priceImpactBps", type: "int32" },
    ],
    anonymous: false,
  },
] as const;
